name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
        
      # a standard step for GitHub actions on Node
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          # update the Node version to meet your needs
          node-version: 16
          cache: npm

      - name: Build
        run: |
          sed -i 's/wordcloud.png/wordcloud${{ github.sha }}.png/g' data/siteMetadata.js
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: generate word cloud
        run: |
          pip install wordcloud
          wordcloud_cli --text tags.txt --mode RGBA --background None --imagefile out/static/images/wordcloud${{ github.sha }}.png

      - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: blog
          folder: out